### ISSUE TITLE
`gen5-mold` clean-ups

### ISSUE THREAD

**Issue by kamangir** [kamangir/ferfereh#4]
- [x] how are we holding the `3mm` shaft inside the mold?
   ![image](https://user-images.githubusercontent.com/1007567/187057768-96135097-e744-4522-b070-d499b6c5d7f8.png)
- [x] what is wrong w/ `gen5-mold-b`?
   <img width="1136" alt="image" src="https://user-images.githubusercontent.com/1007567/187058152-47b1231d-0ade-432e-8747-75aa0f8c47ed.png">
- [x] what is wrong w/ `gen5-mold-m`?
    <img width="1136" alt="image" src="https://user-images.githubusercontent.com/1007567/187058193-b4b4d3ed-9e29-4a1d-a746-2a6f2b8d26d0.png">

**Comment by 1baabak** [comment]
Probably need to have a hole in the middle of the base to hold the shaft.
And need to have something on the top to keep the shaft center while pouring the concrete, don't we?
